[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

; --- COMPILER OVERRIDES ---
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -Wno-pragmas  ; <--- Forces the compiler to silence the SPI warning
    -Wno-cpp      ; <--- Silences #warning directives
board_build.flash_mode = dio

; --- LIBRARIES ---
lib_deps =
    majicdesigns/MD_MAX72XX @ ^3.5.1
    kosme/arduinoFFT @ ^2.0.2
    tzapu/WiFiManager @ ^2.0.17
    ayushsharma82/ElegantOTA @ ^3.1.0

; --- OTA UPLOAD SETTINGS ---
upload_protocol = espota
upload_port = glowbar.local
